version: "3.9"

networks:
  redpanda_network:
    driver: bridge

services:

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19093
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19093
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
    ports:
      - 18081:8081
      - 18082:8082
      - 9093:9092
      - 19644:9644
    volumes:
      - ./kafka:/tmp/data
    networks:
      - redpanda_network
  
  console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: console
    ports:
      - 8080:8080
    networks:
      - redpanda_network
    depends_on:
      - redpanda
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:18081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
  
  spark-master:
    image: cluster-apache-spark:3.2.1
    container_name: spark-master
    ports:
      - "9095:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
    networks:
      - redpanda_network

  spark-worker-a:
    image: cluster-apache-spark:3.2.1
    container_name: spark-worker-a
    ports:
      - "9096:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=3G
      - SPARK_DRIVER_MEMORY=3G
      - SPARK_EXECUTOR_MEMORY=3G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    networks:
      - redpanda_network

  spark-worker-b:
    image: cluster-apache-spark:3.2.1
    container_name: spark-worker-b
    ports:
      - "9097:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=3G
      - SPARK_DRIVER_MEMORY=3G
      - SPARK_EXECUTOR_MEMORY=3G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
        - ./apps:/opt/spark-apps
        - ./data:/opt/spark-data
    networks:
      - redpanda_network